[versions]
jackson = "2.14.2"
retrofit = "2.9.0"

[libraries]
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jacksonAnnotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jacksonJsonSchema = { module = "com.kjetland:mbknor-jackson-jsonschema_2.12", version = "1.0.34" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.24" }
junitBom = { module = "org.junit:junit-bom", version = "5.8.2" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitJackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit" }
retrofitRxJava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
retrofitMock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }
jtokkit = { module = "com.knuddels:jtokkit", version = "0.5.1" }
mockito = { module = "org.mockito:mockito-core", version = "3.12.4" }
assertj = { module = "org.assertj:assertj-core", version = "3.21.0" }